version: "3.9"

services:
  db:
    image: postgres:alpine
    container_name: postgres-db
    env_file: ".env"
    ports:
      - "5432:5432"

  web:
    build:
      context: .
    ports:
      - "8002:8000"
    depends_on:
      - db
